"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_bg = '#282828'
color_red = '#cc241d'
color_green = "#98971a"
color_yellow = "#d79921"
color_blue = "#458588"
color_purple = "#b16286"
color_aqua = "#689d6a"
color_gray = "#a89984"

[character]
success_symbol = '[](bold color_yellow)'
error_symbol = '[](bold color_red)'
vicmd_symbol = '[](bold color_green)'

[git_status]
ahead = '[A](bold color_purple)'
behind = '[B](bold color_purple)'
staged = '[S](bold color_green)'
deleted = '[D](bold color_red)'
renamed = '[R](bold color_purple)'
stashed = '[](bold color_aqua)'
untracked = '[U](bold color_gray)'
modified = '[M](bold color_blue)'
conflicted = '[](bold color_yellow)'

[python]
symbol = "py "

[c]
symbol = "c "

[lua]
symbol = "lua "

[nodejs]
symbol = "js "

[package]
disabled = true
