## I3status CONFIG by GABRIEL

## GENERAL SETTINGS
general {
	colors = true
	interval = 5
	separator = ""
	color_good = "#98971a"
	color_degraded = "#d78821"
	color_bad = "#cc241d"
	markup = pango
}

## MODULE ORDER

order += "cpu_usage"
order += "memory"
order += "battery all"
order += "volume master"
order += "tztime local"

cpu_usage {
	format = "CPU: %usage"
}

memory {
	format = "MEM: %used"
}

battery all {
	format = "%status %percentage"
	status_bat = "󰂄"
	status_full = "󰁹"
	status_chr = "󰂏"
}

volume master {
	format = "  %volume "
	format_muted = "󰝟 muted"
	device = "pulse:alsa_output.pci-0000_00_0e.0.analog-stereo"
}

tztime local {
	format = "%a, %d %b %R"
}
