#:  _  _____ _____ _______   __   ____ ___  _   _ _____ ___ ____ 
#: | |/ /_ _|_   _|_   _\ \ / /  / ___/ _ \| \ | |  ___|_ _/ ___|
#: | ' / | |  | |   | |  \ V /  | |  | | | |  \| | |_   | | |  _ 
#: | . \ | |  | |   | |   | |   | |__| |_| | |\  |  _|  | | |_| |
#: |_|\_\___| |_|   |_|   |_|    \____\___/|_| \_|_|   |___\____|
#:

#: //============================= THEME ===========================//

#: import theme from ./themes
include ./gruvbox-dark.conf

#: Border when neovim is open
resize_in_steps yes

placement_strategy top-left
#: //============================= FONT ============================//

#: font family
font_family      Monoid Nerd Font Retina
bold_font        auto
italic_font      auto
bold_italic_font auto

#: font size
font_size 12.0

#: disable ligatures under cursor
disable_ligatures cursor

#: default setup
box_drawing_scale 0.001, 1, 1.5, 2


#: //============================= MOUSE ============================//

#: hide mouse cursor after a number of seconds
mouse_hide_wait 3.0

#: color and style for highlighting URL on mouse-over
#: straight, double, curly, dotted, dashed
url_color #cccccc
url_style straight

#: program to open clicked URL
open_url_with default

#: set of URL prefixes to look when detecting URL
url_prefixes file ftp git http https

#: copy to clipboard (or a private buffer) on select
copy_on_select yes

#: remove spaces at the end of lines when copying to clipboard
strip_trailing_spaces never

#: characters considered part of a word when double clicking
select_by_word_characters @-./_~?&=%+#

#: interval between successives clicks to detect double clicks
click_interval -1.0


#: //============================= CURSOR ============================//

#: interval to blick the cursor (0 = don't blick)
cursor_blink_interval 0

#: cursor shape (block, beam, underline)
cursor_shape block


#: //============================= HOTKEYS ============================//

#: like browser navegation
# map ctrl+shift+t new_tab
# map ctrl+shift+w close_tab
# map ctrl+right next_tab
# map ctrl+left previous_tab

#: like vim navegation
# map ctrl+shift+l next_tab
# map ctrl+shift+h previous_tab
# map ctrl+shift+j new_tab
# map ctrl+shift+k close_tab

#: window manager
# map ctrl+shift+m toggle_fullscreen

#: window layout
# enabled_layouts horizontal

#: window layout config
# map ctrl+alt+h goto_layout horizontal
# map ctrl+shift+h neighboring_window left
# map ctrl+shift+l neighboring_window right

//============================= WINDOW ============================//

#: If enable, the window size will be remembered so the new instance will have the same window size
#: If not, the window size will be the initial_window_width/height, in pixels
#: kitty don't center the opened window -> use OS tools like tweaks

# remember_window_size  no
# initial_window_width  1000
# initial_window_height 500

#: background opacity (between 0 - 1.0)
# background_opacity 0.95

#: background color (#2d2a37, #333333)
# background #333333

#: //============================= SHELL ============================//

#: The dafult value . means to use whatever shell is set as default
shell .

#: The terminal based text editor to use when editing the kitty config file
editor .

#: make the cursor shape of block
shell_integration no-cursor

#: disable audio bell
enable_audio_bell no

